version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - auth-network
  app:
    image: 'immobilierdz:latest'
    build:
     context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - rabbitmq
      - keycloakdb
      - discovery
      - gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://keycloakdb:5432/keycloakdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=rabbitmq
      - spring.rabbitmq.addresses=rabbitmq:5672
      - spring.mail.host=maildev
      #- spring_rabbitmq_host=rabbitmq
      #- spring.rabbitmq.addresses=rabbitmq:5672

    networks:
      -  auth-network

  keycloakdb:
    image: 'postgres:14.7-alpine'
    container_name: keycloakdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jdbc:postgresql://keycloakdb:5432/immobilierdz
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
      - auth-network
  discovery:
    image: raniabensakina/eureka:latest
    hostname: discovery
    ports:
        - "8761:8761"
    networks:
      - auth-network

  gateway:
    image: raniabensakina/gateway:latest
    hostname: gateway
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
    ports:
        - "8082:8082"
    depends_on:
      - discovery
    networks:
        - auth-network

  maildev:
    image: maildev/maildev
    container_name: maildev

    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - auth-network
    depends_on:
      - discovery
      - gateway
volumes:
   pgdata:

networks:
  auth-network:
    driver: bridge